/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Sun Feb 05 01:46:56 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


